name: Sample Workflow
on: [push]  # Событие, при котором запускается workflow
jobs:
  build:
    runs-on: ubuntu-latest  # Платформа для запуска задачи
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

name: Build and Test Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build src/YourProject.csproj

name: Parallel Workflow

on: [push]

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build Debug
        run: dotnet build src/YourProject.csproj --configuration Debug

  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build Release
        run: dotnet build src/YourProject.csproj --configuration Release
